### ISSUE TITLE
This is abandoned

### ISSUE THREAD

**Issue by christianbundy** [jsonform/jsonform#115]
This project looks awfully [abandoned](https://github.com/joshfire/jsonform/network) lately.Please feel free to start issues and pull requests at [christianbundy/jsonform](/christianbundy/jsonform). Thanks!

**Comment by tchapi** [comment]
Hi all

In an attempt to make this project regain usefulness and maintainers, I have transfered it to an organization (https://github.com/jsonform) so that interested maintainers can be added to the org directly.

See https://github.com/jsonform/jsonform/issues/177 for details and if you want to participate

Thanks
