### ISSUE TITLE
Updating a tabarray's legend with {{value}} changes the title of all fieldsets

### ISSUE THREAD

**Issue by pedronavf** [jsonform/jsonform#183]
In the JSON Form Playground select the "Templating - tab legend with value and valueInLegend" and add two additional fieldsets, doesn't matter if they have children or not.

When you type something in the text box for the `thoughts[]` field the title for both fieldsets will also change

Below is the JSON schema and its form:
```
{
  "schema": {
    "thoughts": {
      "type": "array",
      "title": "Thoughts",
      "items": {
        "type": "string",
        "title": "A thought",
        "default": "Grmpf"
      }
    }
  },
  "form": [
    {
      "type": "tabarray",
      "items": [
        {
          "type": "section",
          "legend": "{{idx}}. {{value}}",
          "items": [
            {
              "key": "thoughts[]",
              "title": "Thought {{idx}}",
              "valueInLegend": true
            },
            {
              "type": "fieldset",
              "title": "This is a fieldset"
            },
            {
              "type": "fieldset",
              "title": "This is fieldset 2"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by tchapi** [comment]
It indeed looks like a bug. I think it is due to https://github.com/jsonform/jsonform/commit/ab6ebbba02a70b79a44bf2cc30c8cc0e0aa688a9 related to #180.

To fix this without introducing an edge case for #180 I will limit (as per in the docs, by the way) the legend to the direct children (see https://github.com/jsonform/jsonform/wiki#use-a-fields-value-as-tab-legend-with-value-and-valueinlegend) : _"It is restricted to direct children of tabarray fields for the time being"_

**Comment by pedronavf** [comment]
Thanks a lot!
