### ISSUE TITLE
Jsonform questions

### ISSUE THREAD

**Issue by dave-sapienza** [jsonform/jsonform#251]
Hi,
 
I’m write you regards Jsonform and I hope you can help me. My questions are:
 
•         Is there a way to edit dynamically the json schema of the form? I would like to add some properties when a specific value is inserted in the form.
•         Is there a way to access to values of the form without submitting it? On specific event, I would like to change the value of the form and then regenerate the form with the new values.
 
Thank you very much.
 
Best regards

**Comment by tchapi** [comment]
Hi,

  - the json schema is ... JSON, so you can edit it dynamically as a Javascript array, and then re-process it via `$('form').jsonForm({ ... your JSON ... })`
  - you can use any combination of vanilla Javascript or your favorite framework to get the values of the inputs (e.g. `$('#idOfYourInput').val()` in jQuery)

BR

**Comment by Jasata** [comment]
A practical example:

Separate `page-specific.js` for the page where I am using JSONForm.js in (with only essential parts copied here):
```javascript
var formObject = {
    value: null,
    schema: null,
    form: null,
    code: null
};
function clearForm() {
    formObject.value = null;
    formObject.schema = null;
    $('#fileForm').html('');
    $('#fileForm').removeClass();
    // Prompt user to select another file from the list control
    $('#fileForm').addClass('please-choose-file');
}
function loadForm(id) {
    clearForm();
    // Get data
    const xhr_data = new XMLHttpRequest();
    xhr_data.onload = function(e) {
        if (this.status == 200) {
            // Because response is { 'data': { 'col1': .., 'col2': ... } }
            formObject.value = JSON.parse(this.responseText).data;
            renderForm();
        } else {
            // call your error reporting interface here
        }
    };
    xhr_data.open('GET', '/api/file/' + id);
    xhr_data.send();
    // Same for schema
    const xhr_schema = new XMLHttpRequest();
    xhr_schema.onload = function(e) {
        if (this.status == 200) {
            formObject.schema = JSON.parse(this.responseText).schema;
            renderForm();
        } else {
            // call error reporting here
        }
    }
    xhr_schema.open('GET', '/api/file/schema');
    xhr_schema.send();
}
function renderForm() {
    if (formObject.data && formObject.schema) {
        // Mangle your data here, then create the form
        $('#fileForm').jsonForm(formObject);
    }
}
function onSubmitForm(formObj) {
    // 1. mess with your data as much as you need
    // 2. Compile JSON
    // 3. Execute XMLHTTPRequest to API endpoint (send data)
    // On successful send clear the form.
    clearForm();
    // Must NOT let the HTML FORM do anything; return false
    return false;
}
```
And the essential bits from the page:
```html
    <script src="js/page-specific.js"></script>
    <script type="text/javascript" charset="utf-8">
        // JSONForm.js presentation:
        formObject.form = {
            "form": [
                {
                    "key":          "id",
                    "type":         "hidden"
                },
                {
                    "key":          "name",
                    "title":        "File Name",
                    "readonly":     true
                },
                // ... all the form fields
                {
                    "type":          "submit",
                    "title":        "Save"
                }
            ]
        };
        formObject.code = {
            // ... what you need, if any
        };
        // ... 
    </script>

    ...


        <form id="fileForm" class="please-choose-file" onsubmit="return onSubmitForm(this);"></form>

    ...
```

There is a list control on the same page, where by clicking one of the listed files will invoke `loadForm(this.id);`. The `onSubmitForm()` has been left very vague on purpose. My pure REST API needs are unlikely suited for most cases (at least, it seems like most are either FORM posting old-school style or POST'ing JSON to REST API, when the proper method should be PUT and so on and so on...).

*My 2 cents worth on this is that the fact that this (or any other similar solution I have managed to find) does not include the "other half", sending the data, properly implemented, is just mind boggling. Especially since the necessary methods (PUT, PATCH and DELETE) did not make it to HTML5 specifications and FORM tag is utterly unsuitable for REST API interaction - you **need** `XMLHTTPRequest` or other technique. Oh, how wonderful would it have been, if this would have just been a matter of adding another key to the form object and setting the URI, method and event handler(s). If I saw more need for this, other than what I now need to create, I think I would fork this and make it a reality.*

At any rate, I hope this helps someone...
