### ISSUE TITLE
Schema overriding & form elements ordering got mixed up => None Works Good. Also proposed a solution...

### ISSUE THREAD

**Issue by simbeto** [jsonform/jsonform#28]
i really find this plugin useful but also found some issues to its usability & behavior.

``` javascript
schema:{}
```

Above schema is used to define the form schema

``` javascript
form:{}
```

but above form is also used to define (override) the schema And Also to define the ordering of the form elements.  I don't think there is anything that we are overriding here, its all FirstHand definition at the very same form definition file.

**Issues:**
[1]
Just by putting form:{} we entered into both overriding & ordering mode.
Lets say i came here to override 1 field out of 20 in the form But now i have to write the remaining 19 too bcoz' jsonform thinks i am writing the  form element's ordering sequence else they won't show.

[2]
Its not DRY. asking to repeat the same field again in the form:{} just to set its type or css class which could be set inside the schema:{} itself as part of its definition. 
To set a 'field's type textarea'  we have to write it again inside the form:{}

[3]
 '*' practically doesn't seems use-able for ordering purpose.... or any

i am suggesting a modified structure which may solve these issues:

``` javascript
"schema":{
    "names": {
        "title":            "Names",
        "type":             "string",
        "typeOverride":     "textarea",      // **new**
    },
    "dob": {
        "title":            "Date of Birth"
        "type" :            "string",
        "typeOverride":     "date",          // **new**
        "htmlClass":        "calendar",     // **new**
        // any more overriding attribute ...n
    },
"order":{                             // **new**
        "names", "dob"
    },
},
"form":[
    {
        // use this section only for layout specification of the elements
    }
]
```

what u people think?

**Comment by csuwildcat** [comment]
@tidoust just got bit by this issue as well, and wanted to point out that this statement is inaccurate as of 2015: 

> Given a schema, the order of the fields in the form is not defined,
because object properties are not ordered in JavaScript. I know that all
existing browsers and JavaScript environments follow the order of the
properties as they are defined

JavaScript and JSON object properties in all ECMAScript compliant environments (which is all of them, aside from older IE builds) follow a standard, specified ordering, which you can rely on.

**Comment by tidoust** [comment]
> JavaScript and JSON object properties in all ECMAScript compliant environments (which is all of them, aside from older IE builds) follow a standard, specified ordering, which you can rely on.

(For what it's worth, I'm no longer involved in the development of this library)

It is correct that things have changed. The ECMAScript specification now imposes the order of properties (I believe that the right section to look at is [`OwnPropertyKeys`](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-ownpropertykeys)).

Interestingly (or not), the [JSON format](https://tools.ietf.org/html/rfc8259#section-1) itself still considers object properties as unordered. In other words, attaching meaning to the ordering of properties in a JSON object is a JavaScript feature, not a JSON feature (also see the interoperability warning in the definition of [JSON Objects](https://tools.ietf.org/html/rfc8259#section-4) in the IETF RFC). The order of properties could potentially be different if a JSON object is parsed using another language. This does not really affect JSON Form though, since the format is really targeted at being processed with JavaScript.
