### ISSUE TITLE
Are conditional Fields possible?

### ISSUE THREAD

**Issue by SteveG3R** [jsonform/jsonform#312]
Hey Guys,

are conditional fields possible with jsonform?

### My scenario is like this:

Based on a Selection (enum) i want to display different kind of fields in the final form. I tried to use event handlers for this scenario as described in here https://github.com/jsonform/jsonform/wiki#using-event-handlers-to-react-on-fields-updates-in-real-time but i could not figure out the best way to do this yet.

For example:

- If the user will chose "Task" from the selection I would like to show another field. Should I use a CSS Hack (Display "None") for this or is there another way you would recommend?

This is the current schema.
![image](https://user-images.githubusercontent.com/27893204/104304723-093d3580-54cc-11eb-9abb-5bd988d77f50.png)

**Comment by tchapi** [comment]
Would something like this example work ? https://jsonform.github.io/jsonform/playground/index.html?example=fields-selectfieldset

**Comment by SteveG3R** [comment]
Would only work partially since I would also like to use the information of the previous fieldset in the array.

So Array[0] would be Selectvalue '1' -> based on this i want to display a different fieldset for Array[1]. Hope that makes sense.

**Comment by tchapi** [comment]
I guess the most "correct" way would be to `display: none` the fields you don't want with event listeners, so you can have a consistent form structure whatever the _values_ inputted by the user are.

Instead of using `display: none` you could also visually arrange your form so that when a specific value is chosen, one part of the form would fold and another unfold, conveying the meaning that some parts of the form need to be filled depending on the answers you give to certain fields ?
