### ISSUE TITLE
Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by aahnik** [jsonform/jsonform#360]
![image](https://user-images.githubusercontent.com/66209958/121465559-a47efc00-c9d3-11eb-930e-ccfc71bc12be.png)

My json schema https://gist.github.com/aahnik/f614cfce84d89da098d45d97e85d7cdd

What is going wrong. Please help!

**Comment by tchapi** [comment]
See https://github.com/jsonform/jsonform/wiki#outline — you don't have a schema or form property in your object

**Comment by aahnik** [comment]
Hi @tchapi, extremely sorry, to overlook the wiki. I was so excited that I jumped into the playground and pasted my Json schema directly.

I now tried with new json [link](https://gist.github.com/aahnik/f614cfce84d89da098d45d97e85d7cdd), but still not working. I am getting nothing.

**Comment by tchapi** [comment]
You're getting nothing because you explicitely define an empty `form`. Remove it first.
But I notice that you're using `$refs`, that are not yet supported (see https://github.com/joshfire/jsonform/issues/54).

I have had no time to look into this feature for now, but if you're willing to help you're welcome.

**Comment by aahnik** [comment]
thanks a lot for guiding.
